export enum CurrentPage {
  botox = "botox",
  fillers = "fillers",
  laser = "laser",
  body = "body",
  coolSculpt = "coolsculpt",
  emsculpt = "emsculpt",
  vanquish = "vanquish",
  cutera = "cutera",
  aboutUs = "aboutUs",
  jeuveau = "jeuveau",
  daxxify = "daxxify",
  voluma = "voluma",
  volux = "volux",
  rha = "rha",
  restylane = "restylane",
}
