import type { Metadata } from "next";
import "./globals.css";

import ThemeRegistry from "./providers/ThemeRegistry/ThemeRegistry";
import NavBar from "../components/NavBar";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "Aesthetic Surgery & Dermatology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <NavBar />

          {children}
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
